version: 0.0
os: linux
files:
  - source: ./docker-compose.yml
    destination: /home/ec2-user
  - source: ./default.conf
    destination: /home/ec2-user
hooks:
  ApplicationStart:
    - location: scripts/launch_roodeo.sh
      timeout: 300
      runas: root