version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    NODE_OPTIONS: "--max_old_space_size=8192"
phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 164476836539.dkr.ecr.eu-west-3.amazonaws.com
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - export NODE_OPTIONS=--max_old_space_size=8192
      - echo $NODE_OPTIONS
      - cd ./client 
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t roodeo:latest .
      - docker tag roodeo:latest 164476836539.dkr.ecr.eu-west-3.amazonaws.com/roodeo:latest
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push roodeo:latest 164476836539.dkr.ecr.eu-west-3.amazonaws.com/roodeo:latest

