version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    NODE_OPTIONS: "--max_old_space_size=8192"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase...
      - npm install yarn -g
      - cd client && yarn install
      - cd ../interview/client && yarn install
      - cd ../..
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - export NODE_OPTIONS=--max_old_space_size=8192
      - echo $NODE_OPTIONS
      - cd ./client 
      - yarn run build
      - yarn run build-i18n:fr
      - mkdir ../server/public
      - mkdir ../interview-client
      - mkdir ../interview-server
      - cp -R ../interview/server/* ../interview-server
      - cp -R ./dist/client/* ../server/public/
      - cd ../interview/client && yarn run build
      - cp -R ./build/* ../../interview-client
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - 'interview-server/**/*'
    - 'interview-client/**/*'
    - 'server/**/*'
    - 'scripts/**/*'
    - 'appspec.yml'
  name: roodeo

